### ISSUE TITLE
Transfer complex type

### ISSUE THREAD

**Issue by snovik** [MhAllan/TcpServiceCore#10]
Hello.
Complex type not transfer.

I use TcpServiceCore.Test.
Addded complex type:
    [ProtoContract]
    public class BigData
    {
        [ProtoMember(1)]
        public int Value { get; set; }
        [ProtoMember(2)]
        public string StringValue { get; set; }
        [ProtoMember(3)]
        public DateTime DateValue { get; set; }
    }
...

```
        using ((IClientChannel)client)
        {
            BigData bigData = new BigData();
            bigData.Value = 1;
            bigData.StringValue = "data";
            bigData.DateValue = DateTime.Now;
            try
            {
                var result = await client.Echo("message");     <----- all right
                var result2 = await client.GetData();              <----- all right
                var result3 = await client.SetData(bigData);  <----- this place failed. Error:Invalid wire-type; this usually means you have over-written a file without truncating or setting the length; see http://stackoverflow.com/q/2152978/23354   . (with json also does not work), serialization failed?
                Console.WriteLine(result);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
```

**Comment by MhAllan** [comment]
This happened because I modified the emitted proxy to pass multiple parameters, while the server was expecting only one (the multi-parameters feature is not done yet), I mean that the proxy was serializing an array while the server was trying to deserialize the array into one parameter. it is fixed now sorry for this bug, please get latest and update me.

**Comment by snovik** [comment]
Thank you very much for the quick fix. Transfer complex type works. Now it does not work for the function with no parameters (Exception thrown: 'System.IndexOutOfRangeException' in TcpServiceCore.dll). Because msg.Length == 0, and the function is expecting a msg[0] element.

---

I corrected this way:  var message = msg.Length == 0 ? msg : msg[0];

**Comment by MhAllan** [comment]
Correct, anyway, I am done with multiple parameters

**Comment by snovik** [comment]
Tested and works, transfered multiple parameters.
Why the decision to make a const int MIN_BUFFER_SIZE = 64 (BufferManager.cs)?
Transfer an array of 127 bytes as parameter function generates an error ArgumentOutOfRange. I MIN_BUFFER_SIZE expanded to 128 and parameter well transfered.

**Comment by MhAllan** [comment]
Bug fixed. your message will be buffered as long as it fits in the MaxBufferSize you set in the ChannelConfig configuration.

it is 64 KB not 64 (fixed). Why? because less than 64KB is not going to cause memory fragmentation, while bigger byte arrays will cause memory to be fragmented and will lead to OutOfMemoryException (The exact size that cause an object to be allocated in LOH is 85+ KB). So the framework creates pools of buffers like these sizes: 64, 128, 256 ...and so on until your MaxBufferSize. When requests come buffers are created if there is not free buffer in the matching pool and when the request is served the buffer goes back to its pool. so there is no more LOH allocation every request. 

Don't forget to set these configurations (MaxBufferSize  and MaxBufferPoolSize). I will be explaining this buffering in the main page later.

**Comment by snovik** [comment]
Thanks for the detailed answer. It works now.

**Comment by MhAllan** [comment]
Close Issue
